Restore FetchAs with beta Thoth.Json
fable-compiler/fable-fetch pull request #2
Opened 2019-01-14 20:06 UTC by rfrerebe

#1

2019-01-14 20:27 UTC, MangelMaxime requested changes
We removed Thoth.Json depency from Fable.Fetch so people could chose the JSON library they want to use.

Like Fable.SimpleJson, Thoth.Json, their own implementation.

So I am not sure, we want to re-add it to the library or if we want a new package.

2019-01-14 20:27 UTC, MangelMaxime commented on src/Fable.Fetch.fsproj
> +    <PackageReference Include="Thoth.Json" Version="3.0.0-beta-002" />
We should not release a stable version using a beta dependency

2019-01-15 08:45 UTC, rfrerebe commented on src/Fable.Fetch.fsproj
> +    <PackageReference Include="Thoth.Json" Version="3.0.0-beta-002" />
Sure, my idea was to also release a beta version if merged 😄

2019-01-15 09:16 UTC, rfrerebe commented
Ok, I have no issue dropping this PR, but I would welcome a shared vision from fable, safe-stack and Thoth (you), because some packages are deprecated [Fable.PowerPack](https://github.com/fable-compiler/Fable-powerpack), but still referenced in [safe-stack documentation](https://safe-stack.github.io/docs/feature-clientserver-serialization/) and it's not clear from the outside what is the upgrade path.

I did not know about Fable.SimpleJson, and I don't seems to be the only one to find it confusing : https://github.com/Zaid-Ajaj/Fable.SimpleJson/issues/16

I also just learnt about https://github.com/fable-compiler/fable-compiler.github.io/issues/32
which seems a nice solution.

2019-01-15 10:29 UTC, alfonsogarciacaro commented
Actually I wanted to promote more [Fable.SimpleHttp](https://github.com/Zaid-Ajaj/Fable.SimpleHttp) instead of this package, as the API is more idiomatic in F# (specially when combining headers, etc), doesn't require the Fetch polyfill for old browsers and works with F# async.

But I know so many changes in the recommendarions are confusing for users starting the SAFE stack, so I'm not sure 🤔 

Anyway, we can try to finish first https://github.com/fable-compiler/fable-compiler.github.io/issues/32 and see if this helps users (and ourselves!) have a better understanding of the Fable ecosystem 😸

2019-01-15 10:41 UTC, rfrerebe commented
Thanks for your answers.

I am looking forward to this new **packages.fable.io** website.
The fact that Fable.SimpleHttp is more idiomatic is not really a criteria from my point of view, I am more interested in bundle size and if it gets the job done 😄 

I am closing this PR.

2019-01-15 10:41 UTC, closed without merging